EM-aspcore/Models/EmployeeViewModel.cs
using EmAspCore.Entity;
using System.Collections.Generic;

namespace EmAspCore.Models
{
    public class EmployeeViewModel
    {
        // 検索結果の格納
        public List<Employee> employees { get; set; }
        public List<Department> departments { get; set; }

        public string empId { get; set; }
        public string empNm { get; set; }
        public string empKn { get; set; }
        public string mail { get; set; }
        public string newPass { get; set; }
        public string oldPass { get; set; }
        public string confirmPass { get; set; }
        public string department { get; set; }
    }
}

EM-aspcore/Models/ErrorViewModel.cs
using System;

namespace EmAspCore.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

EM-aspcore/Models/LoginModel.cs
namespace EmAspCore.Models
{
    public class LoginModel
    {
    }
}

EM-aspcore/Controllers/ApiController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace EmAspCore.Controllers
{
    [Route("api/[controller]")]
    [ApiController]
    public class ApiController : ControllerBase
    {
        // GET: api/Api
        [HttpGet]
        public IEnumerable<string> Get()
        {
            return new string[] { "value1", "value2" };
        }

        // GET: api/Api/5
        [HttpGet("{id}", Name = "Get")]
        public string Get(int id)
        {
            return "value";
        }

        // POST: api/Api
        [HttpPost]
        public void Post([FromBody] string value)
        {
        }

        // PUT: api/Api/5
        [HttpPut("{id}")]
        public void Put(int id, [FromBody] string value)
        {
        }

        // DELETE: api/ApiWithActions/5
        [HttpDelete("{id}")]
        public void Delete(int id)
        {
        }
    }
}

EM-aspcore/Controllers/DepartmentController.cs
using EmAspCore.Entity;
using EmAspCore.Services;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;

namespace EmAspCore.Controllers
{
    public class DepartmentController : Controller
    {
        // GET: Department
        public ActionResult Index()
        {
            List<Department> departments = new SearchService().SelectAllDepartment();
            return View(departments);
        }

        // GET: Department/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Department/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Department/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: Department/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Department/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: Department/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Department/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

EM-aspcore/Controllers/EmployeeController.cs
using EmAspCore.Entity;
using EmAspCore.Models;
using EmAspCore.Services;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace EmAspCore.Controllers
{
    public class EmployeeController : Controller
    {
        public IActionResult Index()
        {
            EmployeeViewModel model = new EmployeeViewModel();

            // 初期表示用に検索をしておく
            SearchService service = new SearchService();

            // Modelに詰める
            model.employees = service.SelectAllEmployee();
            model.departments = service.SelectAllDepartment();

            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Insert(IFormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here
                // collectionインスタンスから値を受け取りたい・・・
                Employee employee = new Employee();
                employee.employeeName = collection["empNm"];
                employee.employeeKana = collection["empKn"];
                employee.mailAddress = collection["mail"];
                employee.password = collection["newPass"];
                employee.departmentId = int.Parse(collection["department"]);

                // サービスモデルに処理を投げる
                ResistService service = new ResistService();
                service.ResistEmployee(employee);

            }
            catch
            {
            }
            return RedirectToAction(nameof(Index));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Update(IFormCollection collection)
        {
            try
            {
                // TODO: Add update logic here
                // collectionインスタンスから値を受け取りたい・・・
                Employee employee = new Employee();
                employee.employeeId = int.Parse(collection["empId"]);
                employee.employeeName = collection["empNm"];
                employee.employeeKana = collection["empKn"];
                employee.mailAddress = collection["mail"];
                employee.password = collection["newPass"];
                employee.departmentId = int.Parse(collection["department"]);

                // サービスモデルに処理を投げる
                ResistService service = new ResistService();
                service.UpdateEmployee(employee.employeeId, employee);

            }
            catch
            {
            }
            return RedirectToAction(nameof(Index));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(IFormCollection collection)
        {
            try
            {
                int id = int.Parse(collection["empId"]);
                ResistService service = new ResistService();
                service.DeleteEmployee(id);
            }
            catch
            {
                
            }
            return RedirectToAction(nameof(Index));
        }
    }
}

EM-aspcore/Controllers/HomeController.cs
using System.Diagnostics;
using EmAspCore.Models;
using Microsoft.AspNetCore.Mvc;

namespace EmAspCore.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

EM-aspcore/Controllers/LoginController.cs
using Microsoft.AspNetCore.Mvc;

namespace EmAspCore.Controllers
{
    public class LoginController : Controller
    {
        /*
         *  ~/Login　でアクセスする
         * 
         */

        public IActionResult Index()
        {
            return View();
        }

        /*
         * ~/Login/Hello　でアクセスする
         * 
         */
        public string Hello()
        {
            return "とりあえずこれが表示されるならOK？";
        }
    }
}

EM-aspcore/Controllers/MenuController.cs
using Microsoft.AspNetCore.Mvc;

namespace EmAspCore.Controllers
{
    public class MenuController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

EM-aspcore/Views/Department/Create.cshtml
@model EmAspCore.Entity.Department

@{
    ViewData["Title"] = "Create";
}

<h2>Create</h2>

<h4>Department</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="departmentId" class="control-label"></label>
                <input asp-for="departmentId" class="form-control" />
                <span asp-validation-for="departmentId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="departmentNm" class="control-label"></label>
                <input asp-for="departmentNm" class="form-control" />
                <span asp-validation-for="departmentNm" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

EM-aspcore/Views/Department/Edit.cshtml
@model EmAspCore.Entity.Department

@{
    ViewData["Title"] = "Edit";
}

<h2>Edit</h2>

<h4>Department</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="departmentId" class="control-label"></label>
                <input asp-for="departmentId" class="form-control" />
                <span asp-validation-for="departmentId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="departmentNm" class="control-label"></label>
                <input asp-for="departmentNm" class="form-control" />
                <span asp-validation-for="departmentNm" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

EM-aspcore/Views/Department/Index.cshtml
@model IEnumerable<EmAspCore.Entity.Department>

@{
    ViewData["Title"] = "Index";
}

<h2>Index</h2>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.departmentId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.departmentNm)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.departmentId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.departmentNm)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id=item.departmentId }) |
                @Html.ActionLink("Details", "Details", new { id=item.departmentId }) |
                @Html.ActionLink("Delete", "Delete", new { id=item.departmentId })
            </td>
        </tr>
}
    </tbody>
</table>

EM-aspcore/Views/Employee/Index.cshtml
@model EmployeeViewModel

@{
    ViewData["Title"] = "List";
}

<h2>List</h2>

<p>
    <a href="#updateModal" data-toggle="modal" onclick="reflectDialog(null)">Create New</a>
</p>
<table class="table table-hover" id="searchResult">
    <thead>
        <tr>
        <tr>
            <th>社員ID</th>
            <th>社員名</th>
            <th>フリガナ</th>
            <th>メールアドレス</th>
            <th>パスワード</th>
            <th>所属部署</th>
            <th>削除</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var emp in Model.employees)
        {
            <tr>
                <td>
                    <a href="#updateModal" data-toggle="modal"
                       onclick="reflectDialog(@emp.employeeId)">@emp.employeeId</a>
                <td>@emp.employeeName</td>
                <td>@emp.employeeKana</td>
                <td>@emp.mailAddress</td>
                <td>@emp.password</td>
                @foreach (var dep in Model.departments)
                {
                    if (emp.departmentId == dep.departmentId)
                    {
                        <td>@dep.departmentNm</td>
                        break;
                    }
                }
                <td>
                    <a href="#deleteModal" data-toggle="modal"
                       onclick="reflectDelDialog(@emp.employeeId)">
                        <span class="glyphicon glyphicon-remove"></span>
                    </a>
                </td>
            </tr>
        }
    </tbody>
</table>
<div class="modal fade" id="updateModal">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"
                        aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                <h4 class="modal-title">ユーザ情報－<span id="mode"></span></h4>
            </div>
            <form asp-action="Update" id="updateForm" name="updateForm" class="form-horizontal">
                <div class="modal-body">
                    <div id="updErrors"></div>
                    <div class="form-group">
                        <label class="col-xs-3 control-label" for="updateInput_empId">社員ID</label>
                        <div class="col-xs-5">
                            <input type="text" asp-for="empId" id="Input_empId" readonly class="form-control" />
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-xs-3 control-label" for="Input_empNm">社員名</label>
                        <div class="col-xs-5">
                            <input type="text" asp-for="empNm" placeholder="社員名" id="Input_empNm"
                                   class="form-control" />
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-xs-3 control-label" for="Input_empKn">フリガナ</label>
                        <div class="col-xs-5">
                            <input type="text" asp-for="empKn" placeholder="フリガナ" id="Input_empKn"
                                   class="form-control" />
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-xs-3 control-label" for="Input_mail">メールアドレス</label>
                        <div class="col-xs-5">
                            <input type="text" asp-for="mail" placeholder="メールアドレス" id="Input_mail"
                                   class="form-control" />
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-xs-3 control-label"
                               for="updateInput_changePass">パスワード</label>
                        <div class="col-xs-5">
                            <input type="password" asp-for="newPass" placeholder="パスワード" id="Input_pass"
                                   class="form-control" />
                        </div>
                        <span class="help-block text-center" id="passTopic">※変更しない場合は未入力</span>
                        <input type="hidden" id="Org_pass" asp-for="oldPass" />
                    </div>
                    <div class="form-group">
                        <label class="col-xs-3 control-label"
                               for="Input_passConfirm">再入力</label>
                        <div class="col-xs-5">
                            <input type="password" asp-for="confirmPass"
                                   placeholder="再入力" class="form-control" />
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-xs-3 control-label"
                               for="updateInput_department">所属部署</label>
                        <div class="col-xs-5">
                            <select name="department" id="Input_department" onchange="departmentChange();" class="form-control">
                                @foreach (var dep in Model.departments)
                                {
                                    <option value="@dep.departmentId">@dep.departmentNm</option>
                                }
                            </select>
                            <input type="hidden" id="Input_depId" name="depId" />
                            <input type="hidden" id="Input_depNm" name="depNm" />
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <input type="submit" class="btn btn-info" id="btnRegist" />
                    <button type="button" class="btn btn-default" data-dismiss="modal">閉じる</button>
                </div>
            </form>
        </div>
    </div>
</div>
<div class="modal fade" id="deleteModal">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"
                        aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                <h4 class="modal-title">ユーザ情報－削除</h4>
            </div>
            <form asp-action="Delete" name="deleteform" id="delete" class="form-horizontal">
                <div class="modal-body">
                    <p>以下のデータを削除します。よろしいですか？</p>
                    <div class="form-group">
                        <label class="col-xs-3 control-label" for="delete_empId">社員ID</label>
                        <div class="col-xs-5">
                            <input type="text" name="empId" readonly value="" id="delete_empId"
                                   class="form-control" />
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <input type="submit" class="btn btn-info" value="削除">
                    <button type="button" class="btn btn-default" data-dismiss="modal">閉じる</button>
                </div>
            </form>

        </div>
    </div>
</div>
<script type="text/javascript">
    // グローバル変数
    var existsInsError = false;

    // 各ダイアログでの処理
    function departmentChange() {
        $("#Input_depId").val($("#Input_department").val());
        $("#Input_depNm").val($("#Input_department option:selected").text());
    }

    // 一覧「×」押下時のモーダル表示処理
	function reflectDelDialog(target) {
		$("#delete_empId").val(target);
	}

    // キー情報の取り込み処理
    function reflectDialog(target) {
        // 入力項目の初期化
        modalInit();

        let url = $("#updateForm").attr("action");

        if (target == null) {
            // 新規登録用モーダルに切り替え
            $("#mode").text("登録");
            $("#Input_empId").val("IDは自動で割り振られます");
            $("#passTopic").css("visibility", "hidden")
            $("#btnRegist").val("登録");

            url = url.replace("Update", "Insert");
            $("#updateForm").attr("action", url);
        } else {
            // 更新用モーダルに切り替え
            $("#mode").text("更新");
            $("#passTopic").css("visibility", "visible")
            $("btnRegist").val("更新");
            url = url.replace("Insert", "Update");
            $("#updateForm").attr("action", url);

            $("#Input_empId").val(target);

            // 検索しないで画面のある行からデータを反映
            $("#searchResult tbody tr").each(function () {
                var id = $(this).find("td:nth-child(1)").text();
                if (parseInt(id) == target) {
                    $("#Input_empNm").val($(this).find("td:nth-child(2)").text());
                    $("#Input_empKn").val($(this).find("td:nth-child(3)").text());
                    $("#Input_mail").val($(this).find("td:nth-child(4)").text());
                    $("#Input_pass").val($(this).find("td:nth-child(5)").text());
                    //名称を設定
                    $("#Input_depNm").val($(this).find("td:nth-child(6)").text());
                    //名称から値を取得
                    $("#Input_department option").each(function () {
                        if ($("#Input_depNm").val() == $(this).text()) {
                            $("#Input_depId").val($(this).val());
                        }
                    });
                    //コンボボックスを設定
                    $("#Input_department").val($("#Input_depId").val());
                }
            });
        }
    }

    function modalInit() {
        $("#Input_empId").val('');
        $("#Input_empNm").val('');
        $("#Input_empKn").val('');
        $("#Input_mail").val('');
        $("#Input_depNm").val('');
        $("#Input_department").val('10');
    }
</script>

EM-aspcore/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<p>Use this area to provide additional information.</p>

EM-aspcore/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

EM-aspcore/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div id="myCarousel" class="carousel slide" data-ride="carousel" data-interval="6000">
    <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
    </ol>
    <div class="carousel-inner" role="listbox">
        <div class="item active">
            <img src="~/images/banner1.svg" alt="ASP.NET" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Learn how to build ASP.NET apps that can run anywhere.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525028&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner2.svg" alt="Visual Studio" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    There are powerful new features in Visual Studio for building modern web apps.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525030&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner3.svg" alt="Microsoft Azure" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Learn how Microsoft's Azure cloud platform allows you to build, deploy, and scale web apps.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525027&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
    </div>
    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>

<div class="row">
    <div class="col-md-3">
        <h2>Application uses</h2>
        <ul>
            <li>Sample pages using ASP.NET Core MVC</li>
            <li>Theming using <a href="https://go.microsoft.com/fwlink/?LinkID=398939">Bootstrap</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>How to</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=398600">Add a Controller and View</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699315">Manage User Secrets using Secret Manager.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699316">Use logging to log a message.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699317">Add packages using NuGet.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699319">Target development, staging or production environment.</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>Overview</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=518008">Conceptual overview of what is ASP.NET Core</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699320">Fundamentals of ASP.NET Core such as Startup and middleware.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=398602">Working with Data</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=398603">Security</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699321">Client side development</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699322">Develop on different platforms</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699323">Read more on the documentation site</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>Run &amp; Deploy</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=517851">Run your app</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=517853">Run tools such as EF migrations and more</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=398609">Publish to Microsoft Azure Web Apps</a></li>
        </ul>
    </div>
</div>

EM-aspcore/Views/Menu/Index.cshtml
@{
    ViewData["Title"] = "Index";
}

<h2>Index</h2>

EM-aspcore/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - EM_aspcore</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Menu" asp-action="Index" class="navbar-brand">EM-System</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Menu" asp-action="Index">ホーム</a></li>
                    <li><a asp-area="" asp-controller="Employee" asp-action="Index">社員検索</a></li>
                    <li><a asp-area="" asp-controller="Department" asp-action="Index">部署検索</a></li>
                </ul>
            </div>
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2019 - EM_aspcore</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>